package ca.me.proj.api.repository.profile;

import java.util.Optional;
import javax.transaction.Transactional;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;
import ca.me.proj.api.entity.profile.ProfileEntity;
import ca.me.proj.api.repository.base.IBaseRepository;

@Transactional
@Repository
public interface IProfileRepository extends IBaseRepository<ProfileEntity, String> {

        public ProfileEntity findByUsername(String username);

        public boolean existsByUsername(String username);

        // Remove @Override and the @Query annotation to remove native SQL. The method will still
        // work with inferred SQL generated by the method name.
        @Override
        @Query(value = "SELECT * from PROFILE WHERE id = ?1 ", nativeQuery = true)
        public Optional<ProfileEntity> findById(String id);

}
